title: "tmergulhao"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://tmergulhao.com/" # the base hostname & protocol for your site
permalink: /:categories/:title
include: ['_pages']

sass:
    style:			:compressed

# HTML compressor http://jch.penibelst.de
compress_html:
    clippings: all
    comments: []
    endings: []
    ignore:
    envs: []

gems:
 - jekyll-coffeescript
