baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tmergulhao.com/" # the base hostname & protocol for your site
permalink: /:categories/:title.html

sass:
    style:			:compressed

# HTML compressor http://jch.penibelst.de
compress_html:
    clippings: all
    comments: []
    endings: []
    ignore:
    envs: []
